### ISSUE TITLE
Find out why meta change in beforeRender doesn't work

### ISSUE THREAD

**Issue by pofider** [jsreportonline/main#41] opened 2019-11-14 16:40 UTC
This works on local jsreport

```js
function beforeRender(req, res) {
  res.meta.reportName = 'aaa'
}
```

However it doesn't in jsreportonline or playground. 
The hook needs to run in `afterRender`

https://forum.jsreport.net/topic/1348/setting-default-filename-for-api-response-with-chrome-pdf/5

**Comment by bjrmatos** [comment] 2019-11-22 23:36
actually updating the response should only work in afterRender, because there we intentionally merge back the response https://github.com/jsreport/jsreport-scripts/blob/master/lib/scripts.js#L157 

and in beforeRender it should not work because there we only merge the request object https://github.com/jsreport/jsreport-scripts/blob/master/lib/scripts.js#L151 

it only works on local when using the in-process strategy because the object reference mutated (res.meta) is the same there (before and after the script is executed), for other strategies it does not work, that explains why it does not work on playground and jo.

since this is not a bug, i'm going to close this, if we realize that we want to support this and want to change the behavior of how data is merged in `beforeRender`, `afterRender` then i think the best is to open a new issue.

**Closed as completed by bjrmatos** 2019-11-22 23:36 UTC
